### ISSUE TITLE
clarify format for location (on desktop)

### ISSUE THREAD

**Issue by binyamin** [benyaming/zmanim_bot#35]
Is it a latitude/longitude coordinate? If it's a geotag, what is that?

**Comment by binyamin** [comment]
Related, is there a way to convert a zip code or something into the desired format? Maybe via some api?

**Comment by benyaming** [comment]
Hey
Yes, it is coordinates pair, separated with comma
![image](https://user-images.githubusercontent.com/18378470/119264997-d62f4f00-bbed-11eb-8bb9-5e6c1b5fdd3b.png)

About zip codes - it is interesting idea. There is no lot of users from the USA so far, and zip codes is not too popular in rest of the world :)
But I will research it
